# This rule is not used by the project aqua-scan-gate itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the scans.aquasec.community.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aqua-scan-gate
    app.kubernetes.io/managed-by: kustomize
  name: imagescan-editor-role
rules:
- apiGroups:
  - scans.aquasec.community
  resources:
  - imagescans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scans.aquasec.community
  resources:
  - imagescans/status
  verbs:
  - get
